import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { z } from "zod";

// Server-only content layer. Reads markdown files from /content, validates
// their frontmatter against the schemas below (the single source of truth for
// both runtime validation and TypeScript types), and returns typed objects.
//
// Design note: schemas are `strictObject` so an unknown frontmatter key (a typo
// like `githbub` or `catgory`) is a hard error, not a silently ignored field.
// This matters because content will eventually be generated by agents — a clear
// error at load time beats a page that renders wrong.

const CONTENT_DIR = path.join(process.cwd(), "content");

// --- Schemas (source of truth) ---

const linksSchema = z.strictObject({
  demo: z.url().optional(),
  github: z.url().optional(),
  other: z.url().optional(),
});

export const projectSchema = z.strictObject({
  title: z.string().min(1),
  slug: z.string().min(1),
  date: z.coerce.date({ error: "manca o non è una data valida (usa YYYY-MM-DD)" }),
  status: z.enum(["wip", "completed"]),
  summary: z.string().min(1),
  tags: z.array(z.string()).default([]),
  stack: z.array(z.string()).default([]),
  links: linksSchema.default({}),
  cover: z.string().optional(),
  featured: z.boolean().default(false),
});

export const interestSchema = z.strictObject({
  title: z.string().min(1),
  slug: z.string().min(1),
  date: z.coerce.date({ error: "manca o non è una data valida (usa YYYY-MM-DD)" }),
  category: z.enum(["gym", "gaming", "music", "movies", "other"]),
  summary: z.string().min(1),
  tags: z.array(z.string()).default([]),
  cover: z.string().optional(),
});

// --- Types (inferred from schemas) ---

export type ProjectStatus = z.infer<typeof projectSchema>["status"];
export type InterestCategory = z.infer<typeof interestSchema>["category"];
export type Project = z.infer<typeof projectSchema> & { body: string };
export type Interest = z.infer<typeof interestSchema> & { body: string };

// --- Loader ---

const byDateDesc = (a: { date: Date }, b: { date: Date }) =>
  b.date.getTime() - a.date.getTime();

function loadCollection<T extends { slug: string }>(
  dir: string,
  schema: z.ZodType<T>,
): (T & { body: string })[] {
  const abs = path.join(CONTENT_DIR, dir);
  if (!fs.existsSync(abs)) return [];

  return fs
    .readdirSync(abs)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const raw = fs.readFileSync(path.join(abs, file), "utf8");
      const { data, content } = matter(raw);

      const parsed = schema.safeParse(data);
      if (!parsed.success) {
        const issues = parsed.error.issues
          .map((i) => `  - ${i.path.join(".") || "(root)"}: ${i.message}`)
          .join("\n");
        throw new Error(`Invalid frontmatter in content/${dir}/${file}:\n${issues}`);
      }

      // Slug must match filename, so URLs and files stay in lockstep.
      const expected = file.replace(/\.md$/, "");
      if (parsed.data.slug !== expected) {
        throw new Error(
          `Slug mismatch in content/${dir}/${file}: frontmatter slug "${parsed.data.slug}" != filename "${expected}"`,
        );
      }

      return { ...parsed.data, body: content };
    });
}

// --- Public API ---

export type ProjectFilter = { tag?: string; status?: ProjectStatus; featured?: boolean };

export function getAllProjects(filter: ProjectFilter = {}): Project[] {
  let items = loadCollection("projects", projectSchema).sort(byDateDesc);
  if (filter.tag) items = items.filter((p) => p.tags.includes(filter.tag!));
  if (filter.status) items = items.filter((p) => p.status === filter.status);
  if (filter.featured !== undefined) items = items.filter((p) => p.featured === filter.featured);
  return items;
}

export function getProjectBySlug(slug: string): Project | undefined {
  return getAllProjects().find((p) => p.slug === slug);
}

export type InterestFilter = { tag?: string; category?: InterestCategory };

export function getAllInterests(filter: InterestFilter = {}): Interest[] {
  let items = loadCollection("interests", interestSchema).sort(byDateDesc);
  if (filter.tag) items = items.filter((i) => i.tags.includes(filter.tag!));
  if (filter.category) items = items.filter((i) => i.category === filter.category);
  return items;
}

export function getInterestBySlug(slug: string): Interest | undefined {
  return getAllInterests().find((i) => i.slug === slug);
}
